import { shuffleArray } from '../common'

const wordList = [
  'Decentralization',
  'Cryptocurrency',
  'Bitcoin',
  'Ethereum',
  'Polygon',
  'Collectible',
  'Blockchain',
  'Marketplace',
  'Token',
  'Ownership',
  'Rarity',
  'Minting',
  'Metaverse',
  'Decentraland',
  'Avatar',
  'Virtual world',
  'Virtual reality',
  'Digital identity',
  'Augmented reality',
  'Wallet',
  'Network',
  'Altcoin',
  'Portfolio',
  'Smart contract',
  'Digital asset',
  'Wearable',
  'Transaction',
  'Security',
  'Rug pull',
  'Governance',
  'Whitelist',
  'Bear market',
  'Bull market',
  'Community',
  'Private key',
  'Public key',
  'Liquidity',
  'Staking',
  'Protocol',
  'Interoperability',
  'Zero knowledge',
  'Scalability',
  'Bytecode',
  'Optimistic rollup',
  'Value layer',
  'User experience',
  'Sidechain',
  'Transparency',
  'Seed phrase',
  'Mainnet'
]

export const getShuffledWordList = (): string[] => shuffleArray([...wordList])
